services:
  quiz:
    image: quizzapp:latest
    container_name: quiz
    networks:
      - lan
#    ports:
#      - 3000:3000
    volumes:
      - db:/app/db
    labels:
      com.centurylinklabs.watchtower.enable: false
      caddy: "import rpa {{upstreams 3000}} quiz _"

networks:
  lan:
    external: true

volumes:
  db:

