apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-pod-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  labels:
    app: node-app
spec:
  containers:
  - name: node-container
    image: node:18-alpine
    command: ["/bin/sh"]
    args: 
    - -c
    - |
      apk add --no-cache bash git
      if [ -f /app/quizzapp/start.sh ]; then
        cd /app/quizzapp
        npm install -g ts-node 2>/dev/null || true
        npm install 2>/dev/null || true
        nohup ./start.sh > /tmp/app.log 2>&1 &
      fi
      tail -f /dev/null
    ports:
    - containerPort: 3000
      name: http
    volumeMounts:
    - name: node-storage
      mountPath: /app
    env:
    - name: NODE_ENV
      value: "development"
  volumes:
  - name: node-storage
    persistentVolumeClaim:
      claimName: node-pod-pvc
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: node-pod-service
spec:
  type: LoadBalancer
  selector:
    app: node-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
